name = "TimeTraveller"
uuid = "94ef9ff7-d57b-4292-b22e-937746d3b81b"
authors = ["Frames White <me@oxinabox.net> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
